[tool.black]
line-length = 119  # if changed, change it for flake8, pylint, isort
skip-string-normalization = 1
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
