name: kisaweb
env:
  APPLICATION_NAME : "kisaweb"

on: [push]

jobs:
  run-tests:

    runs-on: [ubuntu-18.04]

    steps:
      - name: python3 -V
        run: python3 -V
    
#       - name: remove python 3.7
#         run: sudo apt-get remove -y python

#       - name: remove python 3.7
#         run: sudo apt-get remove -y python3-pip

      - name: udate and upgrade
        run: sudo apt-get update && sudo apt-get upgrade

      - name: install python 3.7
        run: sudo apt-get install -y python3.7
      - name: python3 -V
        run: python3 -V
    
      - name: Clone repository
        uses: actions/checkout@v1

      - name: install pip
        run: sudo apt-get install -y python3-pip

      - name: install pip
        run: pip install -U django==3.0

      - name: Installing requriments
        run: pip install -r requirements.txt

      - name: pre-commit install
        run: pre-commit install

      - name: pre-commit autoupdate
        run: pre-commit autoupdate

      - name: git config core.hookspath .githooks
        run: git config core.hookspath .githooks

      - name: Run
        run: |
          cd web
          python3 manage.py migrate

